CREATE TABLE products (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    category_id TINYINT,

    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT
);